const menu = [
    {
        id: 1,
        title: 'Яичница',
        category: 'breakfast',
        price: 15.99,
        img: "https://img1.russianfood.com/dycontent/images_upl/353/sm_352910.jpg",
        desc: `Один из самых быстрых, но вкусных завтраков - это яичница. `,
    },
    {
        id: 2,
        title: 'Мясо, жаренное с перцем',
        category: 'lunch',
        price: 13.99,
        img: "https://img1.russianfood.com/dycontent/images_upl/8/sm_7600.jpg",
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
        id: 3,
        title: 'Самса с мясом и картофелем',
        category: 'snakes',
        price: 6.99,
        img:'https://img1.russianfood.com/dycontent/images_upl/270/sm_269025.jpg',
    },
    {
        id: 4,
        title: 'Манная каша',
        category: 'breakfast',
        price: 20.99,
        img: "https://img1.russianfood.com/dycontent/images_upl/506/sm_505875.jpg",
        desc: `
От такой манной каши не откажется ни один привереда - нежная, воздушная манка на молоке выглядит очень аппетитно и неузнаваемо!`,
    },
    {
        id: 5,
        title: 'Сазан запеченный',
        category: 'lunch',
        price: 22.99,
        img: 'https://img1.russianfood.com/dycontent/images_upl/211/sm_210236.jpg',
        desc: `Сазан, запечённый с лимоном на луковой "подушке", вместе с картофелем-гарниром.`,
    },
    {
        id: 6,
        title: 'Чизкейк',
        category: 'snakes',
        price: 18.99,
        img: 'https://img1.russianfood.com/dycontent/images_upl/147/sm_146553.jpg',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 7,
        title: 'Жидкая овсяная каша на молок',
        category: 'breakfast',
        price: 8.99,
        img:'https://img1.russianfood.com/dycontent/images_upl/579/sm_578333.jpg',
        desc: ` Сытный, полезный, а главное - вкусный завтрак! `,
    },
    {
        id: 8,
        title: 'Картофель, фаршированный грибами',
        category: 'lunch',
        price: 12.99,
        img: 'https://img1.russianfood.com/dycontent/images_upl/175/sm_174763.jpg',
        desc: `Блюда, приготовленные из картофеля и грибов, очень вкусные и популярные.`,
    },
    {
        id: 9,
        title: 'Торт лимонный',
        category: 'snakes',
        price: 16.99,
        img:'https://img1.russianfood.com/dycontent/images_upl/1/sm_571.jpg',
        desc: `И помните, что "плюсов" у сладостей всегда больше, чем "минусов"! :)`,
    },
];
export default menu;